name: Alpha1 CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run basic tests
      - name: Run tests
        shell: pwsh
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}


        run: |
          echo "Running sanity check..."
          # Set both PYTHONPATH and UTF-8 encoding
          $env:PYTHONPATH = "."
          [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
          
          # Test the import (with simple text to ensure it works)
          python -c "import Alpha1; print('App imported successfully!')"
